#!/usr/bin/python

# This is a simple echo bot using the decorator mechanism.
# It echoes any incoming text messages.

import telebot

API_TOKEN = 7241882823:AAGKvbPPoXkb_SbMysScNSYFdaATI2Jm824

bot = telebot.TeleBot(API_TOKEN)


# Handle '/start' and '/help'
@bot.message_handler(commands=['help', 'start'])
def send_welcome(message):
    bot.reply_to(message, """\
FRATMO benvenuto in CEnoSmoke
Consegne su tutto il territorio
""")


# Handle all other messages with content_type 'text' (content_types defaults to ['text'])
@bot.message_handler(func=lambda message: True)
def echo_message(message):
if message.text== 'Ciao':
 bot.reply_to(message, Ciao fratmo, benvenuto su CEnoSmoke, effettuiamo Consegne su tutto il territorio Castellano,
t.me/jcastelvolturno


bot.infinity_polling()
